name: Code and Project Insights

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-code-insights:
    name: Update Code and Project Insights
    runs-on: ubuntu-latest
    steps:
      - uses: RashmikaRamkumar/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "Code and Project Insights"
          SHOW_COMMIT: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_TIMEZONE: False
          SHOW_OS: False
          SHOW_EDITORS: False
