name: Productivity Metrics

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-productivity:
    name: Update Productivity Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: RashmikaRamkumar/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "Productivity Metrics"
          SHOW_LANGUAGE: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
