name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: RashmikaRamkumar/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"  # Show lines of code written
          SHOW_TOTAL_CODE_TIME: "True"  # Show total code time
          SHOW_PROFILE_VIEWS: "True"  # Show profile views
          SHOW_LOC_CHART: "False"  # Hide the lines of code chart
          SYMBOL_VERSION: "2"  # Set the symbol version for the progress bar to 2
